import type { KairosTask, KairosConfig } from "./types";
import path from "path";
import { MemorySystem } from "@cowork/core";

/**
 * Central dispatcher — routes a task to its handler by task.id prefix.
 */
export async function executeKairosTask(
  task: KairosTask,
  config: KairosConfig
): Promise<void> {
  if (task.id.startsWith("dream:")) {
    await runDream(config);
  } else if (task.id.startsWith("digest:")) {
    await runDigest(config);
  } else if (task.id.startsWith("research:")) {
    await runResearch(task, config);
  } else if (task.id.startsWith("wiki:")) {
    await runWikiSync(task, config);
  } else if (task.id.startsWith("gc:")) {
    await runGarbageCollect(config);
  } else {
    throw new Error(`Unknown KAIROS task id prefix: "${task.id}"`);
  }
}

// ── Dream: nightly memory consolidation ──────────────────────────────────────
async function runDream(config: KairosConfig): Promise<void> {
  const memory = new MemorySystem({ projectRoot: config.projectRoot });
  const { AutoDream } = await import("@cowork/core");
  const dream = new AutoDream(memory);
  await dream.consolidate();
}

// ── Digest: write a daily summary to memory ──────────────────────────────────
async function runDigest(config: KairosConfig): Promise<void> {
  const memory = new MemorySystem({ projectRoot: config.projectRoot });
  const today = new Date().toISOString().slice(0, 10);
  const root = (MemorySystem as any).rootFor(config.projectRoot);
  const transcriptPath = path.join(
    root,
    "transcripts",
    `${today}.md`
  );
  let transcriptContent = "";
  try {
    transcriptContent = await Bun.file(transcriptPath).text();
  } catch {
    return; // no transcript today yet, skip
  }
  if (!transcriptContent.trim()) return;

  await memory.save({
    type: "project",
    sessionId: "kairos-digest",
    name: `daily-digest-${today}`,
    description: `Auto-generated daily digest for ${today}`,
    body: `Daily digest auto-generated by KAIROS.\n\nSessions today:\n${transcriptContent.slice(0, 4000)}`,
    tags: ["digest", "daily", today],
    confidence: 0.7,
  });
}

// ── Research: placeholder — calls AutoResearch package ───────────────────────
async function runResearch(task: KairosTask, config: KairosConfig): Promise<void> {
  // @ts-ignore
  const { AutoResearch } = await import("@cowork/research");
  const research = new AutoResearch({ ...config, taskMeta: task });
  await research.runBackgroundPass();
}

// ── Wiki sync: keep LLMWiki up-to-date ───────────────────────────────────────
async function runWikiSync(task: KairosTask, config: KairosConfig): Promise<void> {
  // @ts-ignore
  const { LLMWiki } = await import("@cowork/wiki");
  const wiki = new LLMWiki({ projectRoot: config.projectRoot });
  await wiki.syncFromMemory();
}

// ── GC: purge old transcripts beyond retention window ────────────────────────
async function runGarbageCollect(config: KairosConfig): Promise<void> {
  const root = (MemorySystem as any).rootFor(config.projectRoot);
  const transcriptDir = path.join(
    root,
    "transcripts"
  );
  const retentionDays = 90;
  const cutoff = Date.now() - retentionDays * 24 * 60 * 60 * 1000;

  const glob = new (await import("bun")).Glob("*.md");
  for await (const file of glob.scan({ cwd: transcriptDir, onlyFiles: true })) {
    const dateStr = file.replace(".md", "");
    const ts = new Date(dateStr).getTime();
    if (!isNaN(ts) && ts < cutoff) {
      try {
        const { unlink } = await import("node:fs/promises");
        await unlink(path.join(transcriptDir, file));
      } catch { /* best effort */ }
    }
  }
}
