import type { KairosTask, KairosConfig } from "./types";
import path from "node:path";
import { MemorySystem } from "@cowork/core";
import { WikiStore } from "@cowork/wiki";

/**
 * Central dispatcher — routes a task to its handler by task.id prefix.
 */
export async function executeKairosTask(
  task: KairosTask,
  config: KairosConfig
): Promise<void> {
  if (task.id.startsWith("dream:")) {
    await runDream(config);
  } else if (task.id.startsWith("digest:")) {
    await runDigest(config);
  } else if (task.id.startsWith("research:")) {
    await runResearch(task, config);
  } else if (task.id.startsWith("wiki:")) {
    await runWikiSync(task, config);
  } else if (task.id.startsWith("gc:")) {
    await runGarbageCollect(config);
  } else {
    throw new Error(`Unknown KAIROS task id prefix: "${task.id}"`);
  }
}

// ── Dream: nightly memory consolidation ──────────────────────────────────────
async function runDream(config: KairosConfig): Promise<void> {
  const transcriptDir = path.join(
    MemorySystem.rootFor(config.projectRoot),
    "transcripts"
  );
  try {
    const { Glob } = await import("bun");
    const glob = new Glob("*.md");
    const files = Array.from(glob.scanSync({ cwd: transcriptDir, onlyFiles: true }));
    if (files.length === 0) return;

    // Pick the most recent transcript
    const latestFile = files.sort().pop()!;
    const fileContent = await Bun.file(path.join(transcriptDir, latestFile)).text();

    if (!fileContent.trim()) return;

    const wiki = new WikiStore(config.projectRoot);
    await wiki.init();
    await wiki.upsertPage(`autodream-${latestFile.replace('.md', '')}`, {
      title: `Consolidated Knowledge: ${latestFile}`,
      body: `Auto-consolidated from transcript ${latestFile}.\n\n${fileContent.slice(0, 5000)}`,
      tags: ["autodream", "auto-generated"],
      sourceMemoryIds: [],
    });
    console.log(`[KAIROS] AutoDream consolidated ${latestFile} to WikiStore.`);
  } catch (err) {
    console.error("[KAIROS] AutoDream failed:", err);
  }
}

// ── Digest: write a daily summary to memory ──────────────────────────────────
async function runDigest(config: KairosConfig): Promise<void> {
  const memory = new MemorySystem({ projectRoot: config.projectRoot });
  const today = new Date().toISOString().slice(0, 10);
  const transcriptPath = path.join(
    MemorySystem.rootFor(config.projectRoot),
    "transcripts",
    `${today}.md`
  );
  let transcriptContent = "";
  try {
    const file = Bun.file(transcriptPath);
    transcriptContent = await file.text();
  } catch {
    return; // no transcript today yet, skip
  }
  if (!transcriptContent.trim()) return;

  await memory.save({
    type: "project",
    name: `daily-digest-${today}`,
    description: `Auto-generated daily digest for ${today}`,
    body: `Daily digest auto-generated by KAIROS.\n\nSessions today:\n${transcriptContent.slice(0, 4000)}`,
    tags: ["digest", "daily", today],
    confidence: 0.7,
    sessionId: null,
  });
}

// ── Research: placeholder — calls AutoResearch package ───────────────────────
async function runResearch(task: KairosTask, config: KairosConfig): Promise<void> {
  // Dynamically imported to keep kairos lightweight
  const { AutoResearch } = await import("@cowork/research");
  const research = new AutoResearch({ ...config, projectRoot: config.projectRoot, taskMeta: task as any });
  await research.runBackgroundPass();
}

// ── Wiki sync: keep WikiStore up-to-date ───────────────────────────────────────
async function runWikiSync(task: KairosTask, config: KairosConfig): Promise<void> {
  // Legacy LLMWiki replaced by WikiStore + sync logic
  // For now, we'll just log that it's pending migration to the new WikiStore sync tools
  console.log("[KAIROS] Wiki sync task pending migration to WikiStore");
}

// ── GC: purge old transcripts beyond retention window ────────────────────────
async function runGarbageCollect(config: KairosConfig): Promise<void> {
  const transcriptDir = path.join(
    MemorySystem.rootFor(config.projectRoot),
    "transcripts"
  );
  const retentionDays = 90;
  const cutoff = Date.now() - retentionDays * 24 * 60 * 60 * 1000;

  const { Glob } = await import("bun");
  const glob = new Glob("*.md");
  for await (const file of glob.scan({ cwd: transcriptDir, onlyFiles: true })) {
    const dateStr = file.replace(".md", "");
    const ts = new Date(dateStr).getTime();
    if (!isNaN(ts) && ts < cutoff) {
      try {
        const { unlink } = await import("node:fs/promises");
        await unlink(path.join(transcriptDir, file));
      } catch { /* best effort */ }
    }
  }
}
